version: '3.9'

services:
  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${DATABASE_PORT}:5432
  osm-tile-server:
    image: overv/openstreetmap-tile-server:2.3.0
    volumes:
      - osm-database:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - ${OSM_TILE_SERVER_PORT}:80
    command: "run"
  osm-overpass:
    image: wiktorn/overpass-api:0.7.56.9
    ports:
      - ${OSM_OVERPASS_PORT}:80
    volumes:
      - osm-overpass:/db/
    environment:
      - OVERPASS_MODE=init
      - OVERPASS_META=yes
      - OVERPASS_PLANET_URL=http://download.geofabrik.de/russia/far-eastern-fed-district-latest.osm.bz2
      - OVERPASS_UPDATE_SLEEP=3600
      - OVERPASS_USE_AREAS=true
      - OVERPASS_STOP_AFTER_INIT=false
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
      start_period: 48h

volumes:
  osm-database:
    external: true
  osm-tiles:
    external: true
  osm-overpass:
    external: true
