version: '3.9'

services:
  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${DATABASE_PORT}:5432
  osm-tile-server:
    image: overv/openstreetmap-tile-server:2.3.0
    volumes:
      - osm-database:/data/database/
    ports:
      - ${OSM_TILE_SERVER_PORT}:80
    command: "run"

volumes:
  osm-database:
    external: true
